interface Candidate {
  platform: string;
  offer: string;
  category: 'Partner Bundles' | 'Student & Education' | 'API Discounts' | 'Annual Savings' | 'Startup Grants' | 'Trials & Free';
  subType?: 'FREE_PLAN' | 'FREE_TRIAL' | 'PROMOTIONAL_FREE' | 'STUDENT_DISCOUNT' | 'ACADEMIC_FREE' | 'STARTUP_GRANT' | 'API_CREDIT' | 'API_RATE_DISCOUNT' | 'ANNUAL_DISCOUNT' | 'PARTNER_BUNDLE';
  status: 'ADD' | 'MONITOR' | 'REJECT';
  reason?: string;
  sourceUrl: string;
  destinationUrl: string;
}

const candidates: Candidate[] = [
  // --- PARTNER BUNDLES ---
  {
    platform: 'Google Pixel',
    offer: '1 Year Google One AI Premium with Pixel Pro',
    category: 'Partner Bundles',
    subType: 'PARTNER_BUNDLE',
    status: 'ADD',
    sourceUrl: 'https://store.google.com/category/phones',
    destinationUrl: 'https://store.google.com/category/phones',
  },
  {
    platform: 'Deutsche Telekom',
    offer: 'Perplexity Pro Mobile Contract Bundle',
    category: 'Partner Bundles',
    subType: 'PARTNER_BUNDLE',
    status: 'ADD',
    sourceUrl: 'https://www.telekom.com/en/media/media-information/archive-news-details/telekom-and-perplexity-bring-ai-to-smartphones',
    destinationUrl: 'https://www.telekom.com/en/media/media-information/archive-news-details/telekom-and-perplexity-bring-ai-to-smartphones',
  },
  {
    platform: 'American Express',
    offer: '$300 ChatGPT Business Statement Credit',
    category: 'Partner Bundles',
    subType: 'PARTNER_BUNDLE',
    status: 'ADD',
    sourceUrl: 'https://www.americanexpress.com/us/credit-cards/business-cards/',
    destinationUrl: 'https://global.americanexpress.com/card-benefits/detail/chatgpt-business-credit/business-platinum',
  },
  {
    platform: 'Samsung',
    offer: 'Galaxy AI Device Features (No Commercial Entitlement)',
    category: 'Partner Bundles',
    subType: 'PARTNER_BUNDLE',
    status: 'REJECT',
    reason: 'Built-in OEM OS feature; no separate commercial AI subscription entitlement or partner voucher.',
    sourceUrl: 'https://www.samsung.com/galaxy-ai/',
    destinationUrl: 'https://www.samsung.com/galaxy-ai/',
  },
  {
    platform: 'Airtel Thanks',
    offer: '12 Months Free Perplexity Pro',
    category: 'Partner Bundles',
    subType: 'PARTNER_BUNDLE',
    status: 'REJECT',
    reason: 'Officially ended January 16, 2026.',
    sourceUrl: 'https://www.airtel.in/perplexity-pro',
    destinationUrl: 'https://www.airtel.in/',
  },
  {
    platform: 'Nothing Technology',
    offer: 'Nothing Phone (2a) Perplexity Pro',
    category: 'Partner Bundles',
    subType: 'PARTNER_BUNDLE',
    status: 'REJECT',
    reason: 'Ended April 30, 2024; destination returns HTTP 404.',
    sourceUrl: 'https://nothing.tech/pages/news',
    destinationUrl: 'https://nothing.tech/pages/news',
  },
  {
    platform: 'SoftBank',
    offer: 'SoftBank 1-Year Perplexity Pro',
    category: 'Partner Bundles',
    subType: 'PARTNER_BUNDLE',
    status: 'REJECT',
    reason: 'Campaign ended; destination returns HTTP 404.',
    sourceUrl: 'https://www.softbank.jp/mobile/special/perplexity/',
    destinationUrl: 'https://www.softbank.jp/mobile/special/perplexity/',
  },

  // --- STUDENT & EDUCATION ---
  {
    platform: 'Perplexity',
    offer: 'Perplexity Education Pro (50% Off SheerID)',
    category: 'Student & Education',
    subType: 'STUDENT_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://www.perplexity.ai/help-center/en/articles/12590157-what-is-education-pro',
    destinationUrl: 'https://www.perplexity.ai/help-center/en/articles/12590157-what-is-education-pro',
  },
  {
    platform: 'Notion AI',
    offer: 'Notion for Education (100% Free Plus Plan)',
    category: 'Student & Education',
    subType: 'ACADEMIC_FREE',
    status: 'ADD',
    sourceUrl: 'https://www.notion.so/product/notion-for-education',
    destinationUrl: 'https://www.notion.com/product/notion-for-education',
  },
  {
    platform: 'Canva AI',
    offer: 'Canva for Education (100% Free K-12 with Magic Studio)',
    category: 'Student & Education',
    subType: 'ACADEMIC_FREE',
    status: 'ADD',
    sourceUrl: 'https://www.canva.com/education/',
    destinationUrl: 'https://www.canva.com/education/',
  },
  {
    platform: 'Figma AI',
    offer: 'Figma for Education (100% Free Professional Plan)',
    category: 'Student & Education',
    subType: 'ACADEMIC_FREE',
    status: 'ADD',
    sourceUrl: 'https://www.figma.com/education/',
    destinationUrl: 'https://www.figma.com/education/',
  },
  {
    platform: 'Weights & Biases',
    offer: 'W&B for Students & Academic Researchers',
    category: 'Student & Education',
    subType: 'ACADEMIC_FREE',
    status: 'ADD',
    sourceUrl: 'https://wandb.ai/site/academic/',
    destinationUrl: 'https://wandb.ai/site/research/',
  },
  {
    platform: 'Hugging Face',
    offer: 'Hugging Face Pro via GitHub Student Developer Pack',
    category: 'Student & Education',
    subType: 'STUDENT_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://education.github.com/pack',
    destinationUrl: 'https://education.github.com/pack',
  },
  {
    platform: 'Google Gemini',
    offer: 'Google AI Student Bundle (Gemini Advanced + YouTube Premium Lite)',
    category: 'Student & Education',
    subType: 'STUDENT_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://one.google.com/about/ai-premium',
    destinationUrl: 'https://one.google.com/about/ai-premium',
  },
  {
    platform: 'ChatGPT',
    offer: 'ChatGPT for Teachers (Free K-12 Workspace)',
    category: 'Student & Education',
    subType: 'ACADEMIC_FREE',
    status: 'ADD',
    sourceUrl: 'https://openai.com/education',
    destinationUrl: 'https://openai.com/education',
  },
  {
    platform: 'Grammarly AI',
    offer: 'Grammarly for Education Campus Plan',
    category: 'Student & Education',
    subType: 'ACADEMIC_FREE',
    status: 'MONITOR',
    reason: 'Institutional sales/quote contact form required; no instant public checkout.',
    sourceUrl: 'https://www.grammarly.com/edu',
    destinationUrl: 'https://www.grammarly.com/edu',
  },
  {
    platform: 'Runway',
    offer: 'Runway Education Discount',
    category: 'Student & Education',
    subType: 'STUDENT_DISCOUNT',
    status: 'REJECT',
    reason: 'Education landing page returns HTTP 404.',
    sourceUrl: 'https://runwayml.com/education',
    destinationUrl: 'https://runwayml.com/education',
  },
  {
    platform: 'Descript',
    offer: 'Descript Education Discount',
    category: 'Student & Education',
    subType: 'STUDENT_DISCOUNT',
    status: 'REJECT',
    reason: 'Education landing page returns HTTP 404.',
    sourceUrl: 'https://www.descript.com/education',
    destinationUrl: 'https://www.descript.com/education',
  },
  {
    platform: 'HeyGen',
    offer: 'HeyGen Education Program',
    category: 'Student & Education',
    subType: 'STUDENT_DISCOUNT',
    status: 'REJECT',
    reason: 'Education landing page returns HTTP 404.',
    sourceUrl: 'https://www.heygen.com/education',
    destinationUrl: 'https://www.heygen.com/education',
  },

  // --- API DISCOUNTS ---
  {
    platform: 'Anthropic API',
    offer: 'Anthropic Prompt Caching (90% Cache Read Discount)',
    category: 'API Discounts',
    subType: 'API_RATE_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching',
    destinationUrl: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching',
  },
  {
    platform: 'Anthropic API',
    offer: 'Anthropic Message Batches API (50% Off)',
    category: 'API Discounts',
    subType: 'API_RATE_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://docs.anthropic.com/en/docs/build-with-claude/batch-processing',
    destinationUrl: 'https://docs.anthropic.com/en/docs/build-with-claude/batch-processing',
  },
  {
    platform: 'DeepSeek',
    offer: 'DeepSeek API Off-Peak 50% Discount',
    category: 'API Discounts',
    subType: 'API_RATE_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://api-docs.deepseek.com/quick_start/pricing/',
    destinationUrl: 'https://api-docs.deepseek.com/quick_start/pricing/',
  },
  {
    platform: 'Groq',
    offer: 'GroqCloud Free Developer API Allowance (14,400 req/day)',
    category: 'API Discounts',
    subType: 'API_CREDIT',
    status: 'ADD',
    sourceUrl: 'https://console.groq.com/docs/rate-limits',
    destinationUrl: 'https://console.groq.com/docs/rate-limits',
  },
  {
    platform: 'Fireworks AI',
    offer: 'Fireworks AI Developer Free Credits ($1 on Signup)',
    category: 'API Discounts',
    subType: 'API_CREDIT',
    status: 'ADD',
    sourceUrl: 'https://fireworks.ai/pricing',
    destinationUrl: 'https://fireworks.ai/pricing',
  },
  {
    platform: 'Together AI',
    offer: 'Together AI Developer Trial Credits ($5 on Signup)',
    category: 'API Discounts',
    subType: 'API_CREDIT',
    status: 'ADD',
    sourceUrl: 'https://www.together.ai/pricing',
    destinationUrl: 'https://www.together.ai/pricing',
  },
  {
    platform: 'Kimi (Moonshot AI)',
    offer: 'Moonshot AI Developer Registration Free Credit (¥15)',
    category: 'API Discounts',
    subType: 'API_CREDIT',
    status: 'ADD',
    sourceUrl: 'https://platform.moonshot.cn/pricing',
    destinationUrl: 'https://platform.moonshot.cn/pricing',
  },
  {
    platform: 'Qwen (Alibaba Cloud)',
    offer: 'Alibaba Cloud DashScope Free Token Allocation',
    category: 'API Discounts',
    subType: 'API_CREDIT',
    status: 'ADD',
    sourceUrl: 'https://www.alibabacloud.com/product/dashscope',
    destinationUrl: 'https://www.alibabacloud.com/product/dashscope',
  },
  {
    platform: 'Cohere',
    offer: 'Cohere Developer Trial API Key (Free Rate Limits)',
    category: 'API Discounts',
    subType: 'API_CREDIT',
    status: 'ADD',
    sourceUrl: 'https://cohere.com/pricing',
    destinationUrl: 'https://cohere.com/pricing',
  },

  // --- ANNUAL SAVINGS ---
  {
    platform: 'Grammarly AI',
    offer: 'Grammarly Annual Billing Discount (60% Savings)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://www.grammarly.com/plans',
    destinationUrl: 'https://www.grammarly.com/plans',
  },
  {
    platform: 'ElevenLabs',
    offer: 'ElevenLabs Annual Subscription Savings (50% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://elevenlabs.io/pricing',
    destinationUrl: 'https://elevenlabs.io/pricing',
  },
  {
    platform: 'Otter.ai',
    offer: 'Otter Pro Annual Billing Discount (40% Savings)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://otter.ai/pricing',
    destinationUrl: 'https://otter.ai/pricing',
  },
  {
    platform: 'Synthesia',
    offer: 'Synthesia Annual Billing Savings (Save 25%–38%)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://www.synthesia.io/pricing',
    destinationUrl: 'https://www.synthesia.io/pricing',
  },
  {
    platform: 'Bolt.new',
    offer: 'Bolt.new Pro Annual Subscription Savings (28% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://bolt.new/pricing',
    destinationUrl: 'https://bolt.new/pricing',
  },
  {
    platform: 'Gamma',
    offer: 'Gamma Plus & Pro Annual Savings (25% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://gamma.app/pricing',
    destinationUrl: 'https://gamma.app/pricing',
  },
  {
    platform: 'Ideogram',
    offer: 'Ideogram 2.0 Annual Subscription Savings (20% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://ideogram.ai/pricing',
    destinationUrl: 'https://ideogram.ai/pricing/',
  },
  {
    platform: 'Runway',
    offer: 'Runway Gen-3/Gen-4 Annual Billing Savings (20% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://runwayml.com/pricing',
    destinationUrl: 'https://runway.com/pricing',
  },
  {
    platform: 'Suno',
    offer: 'Suno Pro & Premier Annual Billing Savings (20% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://suno.com/pricing',
    destinationUrl: 'https://suno.com/pricing',
  },
  {
    platform: 'Leonardo AI',
    offer: 'Leonardo AI Annual Subscription Savings (20% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://leonardo.ai/pricing',
    destinationUrl: 'https://leonardo.ai/pricing',
  },
  {
    platform: 'Midjourney',
    offer: 'Midjourney Annual Subscription Savings (20% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://docs.midjourney.com/docs/plans',
    destinationUrl: 'https://docs.midjourney.com/docs/plans',
  },
  {
    platform: 'Notion AI',
    offer: 'Notion AI Add-On Annual Billing Savings (20% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://www.notion.so/product/ai',
    destinationUrl: 'https://www.notion.com/product/ai',
  },
  {
    platform: 'Replit AI',
    offer: 'Replit Core Annual Subscription Savings (40% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://replit.com/pricing',
    destinationUrl: 'https://replit.com/pricing',
  },
  {
    platform: 'Descript',
    offer: 'Descript Annual Subscription Savings (20% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://www.descript.com/pricing',
    destinationUrl: 'https://www.descript.com/pricing',
  },
  {
    platform: 'HeyGen',
    offer: 'HeyGen Annual Subscription Savings (20% Off)',
    category: 'Annual Savings',
    subType: 'ANNUAL_DISCOUNT',
    status: 'ADD',
    sourceUrl: 'https://www.heygen.com/pricing',
    destinationUrl: 'https://www.heygen.com/pricing',
  },

  // --- STARTUP GRANTS ---
  {
    platform: 'Notion AI',
    offer: 'Notion for Startups (Up to 6 Months Free Business + AI, $12,000 value)',
    category: 'Startup Grants',
    subType: 'STARTUP_GRANT',
    status: 'ADD',
    sourceUrl: 'https://www.notion.so/startups',
    destinationUrl: 'https://www.notion.com/startups',
  },
  {
    platform: 'ElevenLabs',
    offer: 'ElevenLabs Startup Grants (11M Characters/mo for 3 Months, $5,500 value)',
    category: 'Startup Grants',
    subType: 'STARTUP_GRANT',
    status: 'ADD',
    sourceUrl: 'https://elevenlabs.io/startup-grants',
    destinationUrl: 'https://elevenlabs.io/startup-grants',
  },
  {
    platform: 'v0 by Vercel',
    offer: 'Vercel for Startups (Up to $30,000 in Vercel & v0 Credits)',
    category: 'Startup Grants',
    subType: 'STARTUP_GRANT',
    status: 'ADD',
    sourceUrl: 'https://vercel.com/startups',
    destinationUrl: 'https://vercel.com/startups',
  },
  {
    platform: 'OpenAI API',
    offer: 'OpenAI for Startups ($5,000–$100,000 API Credits)',
    category: 'Startup Grants',
    subType: 'STARTUP_GRANT',
    status: 'ADD',
    sourceUrl: 'https://openai.com/startups',
    destinationUrl: 'https://openai.com/startups',
  },
  {
    platform: 'Google Gemini',
    offer: 'Google Cloud AI Startup Program (Up to $200,000 Credits)',
    category: 'Startup Grants',
    subType: 'STARTUP_GRANT',
    status: 'ADD',
    sourceUrl: 'https://cloud.google.com/startup',
    destinationUrl: 'https://cloud.google.com/startup',
  },
  {
    platform: 'ChatGPT',
    offer: 'Microsoft for Startups Founders Hub (Up to $150,000 Azure AI/OpenAI Credits)',
    category: 'Startup Grants',
    subType: 'STARTUP_GRANT',
    status: 'ADD',
    sourceUrl: 'https://startups.microsoft.com/',
    destinationUrl: 'https://startups.microsoft.com/',
  },
  {
    platform: 'Together AI',
    offer: 'Together AI for Startups',
    category: 'Startup Grants',
    subType: 'STARTUP_GRANT',
    status: 'REJECT',
    reason: 'Page returns HTTP 404.',
    sourceUrl: 'https://www.together.ai/startups',
    destinationUrl: 'https://www.together.ai/startups',
  },
  {
    platform: 'Cohere',
    offer: 'Cohere Northstar Startup Program',
    category: 'Startup Grants',
    subType: 'STARTUP_GRANT',
    status: 'REJECT',
    reason: 'Redirects to generic homepage; no public application form.',
    sourceUrl: 'https://cohere.com/startups',
    destinationUrl: 'https://cohere.com/',
  },

  // --- TRIALS & FREE ---
  {
    platform: 'Google NotebookLM',
    offer: 'Google NotebookLM 100% Free Full Access',
    category: 'Trials & Free',
    subType: 'FREE_PLAN',
    status: 'ADD',
    sourceUrl: 'https://notebooklm.google/',
    destinationUrl: 'https://notebook.google/',
  },
  {
    platform: 'Mistral AI',
    offer: 'Mistral Le Chat Free Access with Canvas & Search',
    category: 'Trials & Free',
    subType: 'FREE_PLAN',
    status: 'ADD',
    sourceUrl: 'https://chat.mistral.ai/',
    destinationUrl: 'https://chat.mistral.ai/chat',
  },
  {
    platform: 'Canva AI',
    offer: 'Canva Pro 30-Day Free Trial (Magic Studio Included)',
    category: 'Trials & Free',
    subType: 'FREE_TRIAL',
    status: 'ADD',
    sourceUrl: 'https://www.canva.com/pricing/',
    destinationUrl: 'https://www.canva.com/pricing/',
  },
  {
    platform: 'DeepL Pro',
    offer: 'DeepL Pro 30-Day Free Trial',
    category: 'Trials & Free',
    subType: 'FREE_TRIAL',
    status: 'ADD',
    sourceUrl: 'https://www.deepl.com/pro',
    destinationUrl: 'https://www.deepl.com/en/pro',
  },
  {
    platform: 'Midjourney',
    offer: 'Midjourney Relax GPU Hours Community Perk',
    category: 'Trials & Free',
    subType: 'PROMOTIONAL_FREE',
    status: 'ADD',
    sourceUrl: 'https://docs.midjourney.com/docs/plans',
    destinationUrl: 'https://docs.midjourney.com/docs/plans',
  },
  {
    platform: 'Devin',
    offer: 'Devin Autonomous Engineer Access',
    category: 'Trials & Free',
    subType: 'FREE_TRIAL',
    status: 'REJECT',
    reason: 'Pricing URL returns HTTP 404; preview URL is behind private authentication.',
    sourceUrl: 'https://cognition.ai/pricing',
    destinationUrl: 'https://cognition.ai/pricing',
  },
  {
    platform: 'Phind',
    offer: 'Phind Pro Developer Search',
    category: 'Trials & Free',
    subType: 'FREE_TRIAL',
    status: 'REJECT',
    reason: 'Destination returns HTTP 404 / anti-bot block.',
    sourceUrl: 'https://www.phind.com/',
    destinationUrl: 'https://www.phind.com/',
  },
  {
    platform: 'Character.AI',
    offer: 'c.ai+ Subscription',
    category: 'Trials & Free',
    subType: 'FREE_PLAN',
    status: 'MONITOR',
    reason: 'Standard product pricing ($9.99/mo); no separate promotional offer or discount.',
    sourceUrl: 'https://character.ai/',
    destinationUrl: 'https://character.ai/',
  },
  {
    platform: 'Manus',
    offer: 'Manus Autonomous Agent Access',
    category: 'Trials & Free',
    subType: 'FREE_PLAN',
    status: 'MONITOR',
    reason: 'Closed invitation-only waitlist; no public checkout or verifiable commercial terms.',
    sourceUrl: 'https://manus.im/',
    destinationUrl: 'https://manus.im/',
  },
  {
    platform: 'Lovable',
    offer: 'Lovable Full-Stack Builder Free Tier',
    category: 'Trials & Free',
    subType: 'FREE_PLAN',
    status: 'MONITOR',
    reason: 'Standard 5-credit free tier without time-limited promotion.',
    sourceUrl: 'https://lovable.dev/pricing',
    destinationUrl: 'https://lovable.dev/pricing',
  },
];

const uniquePlatforms = new Set(candidates.map(c => c.platform));
const addCount = candidates.filter(c => c.status === 'ADD').length;
const monitorCount = candidates.filter(c => c.status === 'MONITOR').length;
const rejectCount = candidates.filter(c => c.status === 'REJECT').length;

console.log('=== TALLY AUDIT ===');
console.log('Unique platforms researched:', uniquePlatforms.size);
console.log('Total offer candidates:', candidates.length);
console.log('ADD count:', addCount);
console.log('MONITOR count:', monitorCount);
console.log('REJECT count:', rejectCount);

const byCategory: Record<string, { total: number; add: number; monitor: number; reject: number }> = {};
for (const c of candidates) {
  byCategory[c.category] = byCategory[c.category] || { total: 0, add: 0, monitor: 0, reject: 0 };
  byCategory[c.category].total++;
  if (c.status === 'ADD') byCategory[c.category].add++;
  if (c.status === 'MONITOR') byCategory[c.category].monitor++;
  if (c.status === 'REJECT') byCategory[c.category].reject++;
}

console.log('\n=== BY CATEGORY ===');
console.log(JSON.stringify(byCategory, null, 2));

const bySubType: Record<string, number> = {};
for (const c of candidates) {
  if (c.subType) {
    bySubType[c.subType] = (bySubType[c.subType] || 0) + 1;
  }
}
console.log('\n=== BY SUBTYPE ===');
console.log(JSON.stringify(bySubType, null, 2));
