// ============================================================
// TermsPage — StackSave AI Terms of Service
// Professional, transparent SaaS service terms
// ============================================================

import { Link } from 'react-router-dom';
import Logo from '../components/Logo';
import UserNavMenu from '../components/UserNavMenu';

export default function TermsPage() {
  const lastUpdated = 'September 17, 2026';

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 flex flex-col font-sans">
      {/* Navigation Header */}
      <header className="sticky top-0 z-30 bg-white/90 backdrop-blur-md border-b border-slate-200/80">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Logo size="md" />
            <span className="hidden sm:inline-block text-xs font-semibold px-2 py-0.5 rounded bg-slate-100 text-slate-600 border border-slate-200/60">
              Legal
            </span>
          </div>
          <div className="flex items-center gap-3">
            <Link
              to="/"
              className="text-xs sm:text-sm font-medium text-slate-600 hover:text-slate-900 px-3 py-1.5 rounded-lg hover:bg-slate-100 transition-colors"
            >
              ← Back to StackSave
            </Link>
            <UserNavMenu />
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 max-w-4xl w-full mx-auto px-4 sm:px-6 py-10 sm:py-14">
        <div className="bg-white rounded-2xl border border-slate-200/80 shadow-sm p-6 sm:p-12">
          {/* Header */}
          <div className="border-b border-slate-100 pb-6 mb-8">
            <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
              Terms of Service
            </h1>
            <p className="mt-2 text-sm text-slate-500">
              Last updated: {lastUpdated}
            </p>
          </div>

          <div className="space-y-8 text-sm sm:text-base text-slate-600 leading-relaxed">
            {/* Section 1 */}
            <section>
              <h2 className="text-lg sm:text-xl font-bold text-slate-900 tracking-tight mb-3">
                1. Overview & Acceptance
              </h2>
              <p>
                Welcome to StackSave AI ("StackSave", "we", "us", or "our"). By accessing our website, running an AI spend audit, using our Build My Stack tools, or creating an account via Google Sign-In, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
              </p>
            </section>

            {/* Section 2 */}
            <section>
              <h2 className="text-lg sm:text-xl font-bold text-slate-900 tracking-tight mb-3">
                2. Nature of the Service
              </h2>
              <p className="mb-2">
                StackSave AI provides AI spend intelligence, pricing analytics, software overlap detection, and cost optimization recommendations for software teams and organizations.
              </p>
              <ul className="list-disc pl-5 space-y-1 text-slate-600">
                <li>
                  <strong>Audits & Recommendations:</strong> All estimates, pricing benchmarks, and consolidation savings generated by StackSave are advisory assessments calculated from publicly verified vendor pricing and user-submitted inputs.
                </li>
                <li>
                  <strong>Optional Guest Access:</strong> StackSave remains fully accessible without an account. Running an audit or browsing offers does not require registration.
                </li>
                <li>
                  <strong>Saved Audits & Accounts:</strong> Accounts are optionally created to enable users to save audit histories and track ongoing AI stack intelligence across sessions.
                </li>
              </ul>
            </section>

            {/* Section 3 */}
            <section>
              <h2 className="text-lg sm:text-xl font-bold text-slate-900 tracking-tight mb-3">
                3. Authentication & Account Security
              </h2>
              <p>
                We use Google Identity Services (OAuth 2.0) for frictionless, passwordless authentication. When you sign in with Google, we authenticate your identity and create a secure session. You are responsible for maintaining control of the Google account used to access StackSave. We do not store passwords, and you may sign out or request account deletion at any time.
              </p>
            </section>

            {/* Section 4 */}
            <section>
              <h2 className="text-lg sm:text-xl font-bold text-slate-900 tracking-tight mb-3">
                4. Data Ownership & Privacy
              </h2>
              <p>
                You retain ownership of any data you submit during audits. We do not sell your personal data or audit records to third parties. For complete details regarding information collection, storage, and rights, please review our{' '}
                <Link to="/privacy" className="text-emerald-600 hover:text-emerald-700 font-medium underline underline-offset-2">
                  Privacy Policy
                </Link>.
              </p>
            </section>

            {/* Section 5 */}
            <section>
              <h2 className="text-lg sm:text-xl font-bold text-slate-900 tracking-tight mb-3">
                5. Third-Party Services & Vendor Pricing
              </h2>
              <p>
                StackSave monitors public pricing data for third-party AI platforms (including OpenAI, Anthropic, Cursor, GitHub Copilot, and others). Vendor pricing, subscription tiers, and promotional offers are subject to change by their respective providers. StackSave strives to keep all benchmarks verified and up-to-date, but cannot guarantee real-time vendor price changes.
              </p>
            </section>

            {/* Section 6 */}
            <section>
              <h2 className="text-lg sm:text-xl font-bold text-slate-900 tracking-tight mb-3">
                6. Disclaimer of Warranties & Limitation of Liability
              </h2>
              <p>
                StackSave AI is provided "as is" without warranty of any kind. While our models are designed to maximize software spend efficiency, StackSave is not an authorized reseller, legal advisor, or certified accountant. To the maximum extent permitted by law, StackSave shall not be liable for any indirect, incidental, or consequential damages resulting from your use of the service.
              </p>
            </section>

            {/* Section 7 */}
            <section>
              <h2 className="text-lg sm:text-xl font-bold text-slate-900 tracking-tight mb-3">
                7. Contact Us
              </h2>
              <p>
                If you have questions regarding these Terms of Service, please contact our team at{' '}
                <a href="mailto:support@stacksave.ai" className="text-emerald-600 hover:text-emerald-700 font-medium underline underline-offset-2">
                  support@stacksave.ai
                </a>.
              </p>
            </section>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200/80 bg-white py-6">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-500">
          <p>© {new Date().getFullYear()} StackSave AI. All rights reserved.</p>
          <div className="flex items-center gap-6">
            <Link to="/terms" className="hover:text-slate-900 font-medium text-slate-700">
              Terms of Service
            </Link>
            <Link to="/privacy" className="hover:text-slate-900 transition-colors">
              Privacy Policy
            </Link>
            <Link to="/" className="hover:text-slate-900 transition-colors">
              Home
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
